/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

/**
 *
 * @author Melker
 */
public class Personalmeny extends javax.swing.JFrame {

    /**
     * Creates new form Personalmeny
     */
    public Personalmeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hanteraProdukter = new javax.swing.JButton();
        hanteraForfragan = new javax.swing.JButton();
        skapaForfragan = new javax.swing.JButton();
        hanteraKunder = new javax.swing.JButton();
        goBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        hanteraProdukter.setText("Hantera produkter");
        hanteraProdukter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraProdukterActionPerformed(evt);
            }
        });

        hanteraForfragan.setText("Hantera förfrågningar");
        hanteraForfragan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraForfraganActionPerformed(evt);
            }
        });

        skapaForfragan.setText("Skapa förfrågan");
        skapaForfragan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skapaForfraganActionPerformed(evt);
            }
        });

        hanteraKunder.setText("Hantera kunder");
        hanteraKunder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraKunderActionPerformed(evt);
            }
        });

        goBack.setText("Gå tillbaka");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skapaForfragan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hanteraKunder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hanteraForfragan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hanteraProdukter, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(skapaForfragan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hanteraForfragan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hanteraProdukter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hanteraKunder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hanteraProdukterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraProdukterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HanteraProdukter().setVisible(true);
        
    }//GEN-LAST:event_hanteraProdukterActionPerformed

    private void hanteraForfraganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraForfraganActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HanteraForfragningar().setVisible(true);
    }//GEN-LAST:event_hanteraForfraganActionPerformed

    private void hanteraKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraKunderActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HanteraKunder().setVisible(true);
    }//GEN-LAST:event_hanteraKunderActionPerformed

    private void skapaForfraganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skapaForfraganActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SkapaForfragan().setVisible(true);
        
    }//GEN-LAST:event_skapaForfraganActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inloggningssida().setVisible(true);
    }//GEN-LAST:event_goBackActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBack;
    private javax.swing.JButton hanteraForfragan;
    private javax.swing.JButton hanteraKunder;
    private javax.swing.JButton hanteraProdukter;
    private javax.swing.JButton skapaForfragan;
    // End of variables declaration//GEN-END:variables
}
