/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

/**
 *
 * @author Melker
 */
public class Personalmeny extends javax.swing.JFrame {

    /**
     * Creates new form Personalmeny
     */
    public Personalmeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hanteraProdukter = new javax.swing.JButton();
        hanteraForfragan = new javax.swing.JButton();
        skapaForfragan = new javax.swing.JButton();
        hanteraKunder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        goBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMoms = new javax.swing.JButton();
        OffertKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        hanteraProdukter.setBackground(new java.awt.Color(0, 102, 102));
        hanteraProdukter.setForeground(new java.awt.Color(255, 255, 255));
        hanteraProdukter.setText("Hantera produkter");
        hanteraProdukter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraProdukterActionPerformed(evt);
            }
        });

        hanteraForfragan.setBackground(new java.awt.Color(0, 102, 102));
        hanteraForfragan.setForeground(new java.awt.Color(255, 255, 255));
        hanteraForfragan.setText("Hantera förfrågningar");
        hanteraForfragan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraForfraganActionPerformed(evt);
            }
        });

        skapaForfragan.setBackground(new java.awt.Color(0, 102, 102));
        skapaForfragan.setForeground(new java.awt.Color(255, 255, 255));
        skapaForfragan.setText("Skapa förfrågan");
        skapaForfragan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skapaForfraganActionPerformed(evt);
            }
        });

        hanteraKunder.setBackground(new java.awt.Color(0, 102, 102));
        hanteraKunder.setForeground(new java.awt.Color(255, 255, 255));
        hanteraKunder.setText("Hantera kunder");
        hanteraKunder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraKunderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        goBack.setBackground(new java.awt.Color(102, 102, 102));
        goBack.setForeground(new java.awt.Color(255, 255, 255));
        goBack.setText("Gå tillbaka");
        goBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hattmakarna/kugghjul.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Välj vad du vill göra");

        btnMoms.setBackground(new java.awt.Color(0, 102, 102));
        btnMoms.setForeground(new java.awt.Color(255, 255, 255));
        btnMoms.setText("Moms-sammanställning");
        btnMoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMomsActionPerformed(evt);
            }
        });

        OffertKnapp.setBackground(new java.awt.Color(0, 102, 102));
        OffertKnapp.setForeground(new java.awt.Color(255, 255, 255));
        OffertKnapp.setText("Hämta offert");
        OffertKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffertKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OffertKnapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(skapaForfragan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hanteraKunder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hanteraForfragan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hanteraProdukter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(138, 138, 138)
                .addComponent(skapaForfragan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(hanteraForfragan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hanteraProdukter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hanteraKunder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoms, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OffertKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hanteraProdukterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraProdukterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HanteraProdukter().setVisible(true);
        
    }//GEN-LAST:event_hanteraProdukterActionPerformed

    private void hanteraForfraganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraForfraganActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HanteraForfragningar().setVisible(true);
    }//GEN-LAST:event_hanteraForfraganActionPerformed

    private void hanteraKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraKunderActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HanteraKunder().setVisible(true);
    }//GEN-LAST:event_hanteraKunderActionPerformed

    private void skapaForfraganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skapaForfraganActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SkapaForfragan().setVisible(true);
        
    }//GEN-LAST:event_skapaForfraganActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inloggningssida().setVisible(true);
    }//GEN-LAST:event_goBackActionPerformed

    private void btnMomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMomsActionPerformed
        this.dispose();
        new MomsSammanstallare().setVisible(true);
    }//GEN-LAST:event_btnMomsActionPerformed

    private void OffertKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffertKnappActionPerformed
       this.dispose();
       new VisaOffert().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_OffertKnappActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OffertKnapp;
    private javax.swing.JButton btnMoms;
    private javax.swing.JButton goBack;
    private javax.swing.JButton hanteraForfragan;
    private javax.swing.JButton hanteraKunder;
    private javax.swing.JButton hanteraProdukter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton skapaForfragan;
    // End of variables declaration//GEN-END:variables
}
